import turtle
turtle.pensize(3)
turtle.speed(100)
turtle.color("red")
turtle.begin_fill()
turtle.forward(300)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
turtle.penup()
turtle.goto(20,160)
turtle.pendown()
turtle.pensize(3)
turtle.color("yellow")
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(60)
turtle.right(144)
turtle.forward(60)
turtle.right(144)
turtle.forward(60)
turtle.right(144)
turtle.forward(60)
turtle.right(144)
turtle.forward(60)
turtle.end_fill()
turtle.penup()
turtle.goto(95,185)
turtle.pendown()
turtle.pensize(3)
turtle.color("yellow")
turtle.begin_fill()
turtle.setheading(-30)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.end_fill()
turtle.penup()
turtle.goto(120,170)
turtle.pendown()
turtle.pensize(3)
turtle.color("yellow")
turtle.begin_fill()
turtle.setheading(-60)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.end_fill()
turtle.penup()
turtle.goto(110,132)
turtle.pendown()
turtle.pensize(3)
turtle.color("yellow")
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.end_fill()
turtle.penup()
turtle.goto(90,110)
turtle.pendown()
turtle.pensize(3)
turtle.color("yellow")
turtle.begin_fill()
turtle.setheading(30)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.right(144)
turtle.forward(20)
turtle.end_fill()



















